/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Yc9JXIgyqX7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import {signOut} from "../lib/auth"

export function DisplayAvailablePings() {
  return (
    <div key="1" className="flex flex-col w-full min-h-screen">
     <header className="flex items-center justify-between h-16 px-4 bg-red-500 text-white">
        <Link className="flex items-center gap-2 text-lg font-semibold" href="#">
          <FrameIcon className="w-6 h-6" />
          <span className="sr-only">Rutgers Student App</span>
        </Link>
        <form
          action={async () => {
            "use server";
            await signOut();
          }}
        >
          <button
            type="submit"
            className="px-4 py-2 bg-white text-red-500 rounded-md hover:bg-red-100 focus:outline-none md:ml-auto"
          >
            Sign Out
          </button>
        </form>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10 ">
        <div className="max-w-6xl w-full mx-auto flex items-center justify-center gap-4">
          <div className="relative w-full max-w-md">
            <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
            <Input className="pl-8 w-full" placeholder="Search for available events..." type="search" />
          </div>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 max-w-6xl w-full mx-auto">
          <Card className="bg-white shadow-md">
            <CardHeader className="flex flex-row items-center gap-4 bg-red-500 text-white p-4">
              <MapPinIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>College Ave</CardTitle>
                <CardDescription>Sports</CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <UsersIcon className="w-4 h-4" />
                <span className="text-sm text-white/80">12</span>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2 p-4">
              <div className="text-sm font-semibold">Pickup Basketball Game</div>
              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <MapIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">College Ave Gym</span>
                </div>
                <div className="flex items-center gap-1">
                  <ClockIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">4:00 PM</span>
                </div>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Join fellow students for a pickup basketball game at the College Ave Gym. All skill levels welcome!
              </div>
              <Button className="w-full" >
                Join
              </Button>
            </CardContent>
          </Card>
          <Card className="bg-white shadow-md">
            <CardHeader className="flex flex-row items-center gap-4 bg-red-500 text-white p-4">
              <MapPinIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Busch</CardTitle>
                <CardDescription>Academic</CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <UsersIcon className="w-4 h-4" />
                <span className="text-sm text-white/80">8</span>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2 p-4">
              <div className="text-sm font-semibold">Study Group - Algorithms</div>
              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <MapIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">Busch Library</span>
                </div>
                <div className="flex items-center gap-1">
                  <ClockIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">7:00 PM</span>
                </div>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Join a study group to discuss and work through algorithm problems. All majors welcome!
              </div>
              <Button className="w-full">
                Join
              </Button>
            </CardContent>
          </Card>
          <Card className="bg-white shadow-md">
            <CardHeader className="flex flex-row items-center gap-4 bg-red-500 text-white p-4">
              <MapPinIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Livingston</CardTitle>
                <CardDescription>Sports</CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <UsersIcon className="w-4 h-4" />
                <span className="text-sm text-white/80">15</span>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2 p-4">
              <div className="text-sm font-semibold">Intramural Soccer Game</div>
              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <MapIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">Livingston Turf Field</span>
                </div>
                <div className="flex items-center gap-1">
                  <ClockIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">6:00 PM</span>
                </div>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Join the Livingston intramural soccer team for a friendly game on the turf field. All skill levels
                welcome!
              </div>
              <Button className="w-full">
                Join
              </Button>
            </CardContent>
          </Card>
          <Card className="bg-white shadow-md">
            <CardHeader className="flex flex-row items-center gap-4 bg-red-500 text-white p-4">
              <MapPinIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Cook/Douglass</CardTitle>
                <CardDescription>Academic</CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <UsersIcon className="w-4 h-4" />
                <span className="text-sm text-white/80">10</span>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2 p-4">
              <div className="text-sm font-semibold">Literature Discussion Group</div>
              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <MapIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">Cook Library</span>
                </div>
                <div className="flex items-center gap-1">
                  <ClockIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">8:00 PM</span>
                </div>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Join fellow literature enthusiasts for a discussion on the latest novel. All majors welcome!
              </div>
              <Button className="w-full">
                Join
              </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function ClockIcon(props : any ) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function FrameIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  )
}


function MapIcon(props : any ) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" />
      <path d="M15 5.764v15" />
      <path d="M9 3.236v15" />
    </svg>
  )
}


function MapPinIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function SearchIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UserIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function UsersIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
